# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9c05ed13f2d2148d118766613f473cd4f28965e4c5de5c8fe0ab961deda7e29adc1e3e7e6338534cdc863fefa03a0195a123696441c8a3ad91ecdec810630e0

test:
  secret_key_base: b9cf21ce2ea004722830710d47fd821f4c34a5e3cf3cba565c3e2659de82e7f99b799e516ee15fcdec556fd3f7d1ee6d5877dae354788c834ce54dcad5bac1c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
